<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class about extends CI_Controller
{
    function __construct()
    {
    	
        parent::__construct();
        $this->load->model('gantipass_model');
        if (!$this->session->userdata('logined') ||
		$this->session->userdata('logined') != true)
		{
			redirect('/');
		}

    }

    public function index()
    {
       

        $this->load->view('about/tampilanabout');
        
    } 
    function ubah_password($nama)
	{
		$mhs=$this->gantipass_model->ambil_data_nama($nama);
		$data = array(
			'nama'		=>set_value('nama',$this->session->userdata('nama')),
			'button' => 'Simpan',
			'input' => false,
			'action' => site_url('Mahasiswa/ubah_password_aksi')
			);
		$this->load->view('About/tampilanabout', $data);
	}

	function ubah_password_aksi()
	{
		$nama = $this->input->post('nama');
		$passworddulu = $this->input->post('passworddulu');
		$passwordakan = $this->input->post('passwordakan');
		$mahasiswa=($this->gantipass_model->ambil_data_nama($nama));
		$passvalid = $mahasiswa->pass;
		if($passworddulu == $passvalid){
			$this->gantipass_model->ubah_pass($nama,$passwordakan);
		}
		redirect(site_url('home'));
	}
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */